# Generated by Django 6.0.2 on 2026-08-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('art', 'Art')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('old', 'Old Student'), ('new', 'New Intake')], default='old', max_length=10),
        ),
    ]
