# Generated by Django 6.0.2 on 2026-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feestructure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['student_class', 'student_type', 'department']},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='department',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('art', 'Art')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_type',
            field=models.CharField(choices=[('old', 'Old Student'), ('new', 'New Intake')], default='old', max_length=10),
        ),
    ]
