# Generated by Django 6.0.2 on 2026-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_feestructure_options_feestructure_department_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('session', 'term', 'student_class', 'student_type', 'department'), name='unique_fee_structure'),
        ),
    ]
