# Generated by Django 6.0.2 on 2026-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feestructure_unique_fee_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment')], default='FULL', max_length=10),
        ),
    ]
